### ISSUE TITLE
Bug tickets

### ISSUE THREAD

**Issue by Masadow** [HaxeBeluga/beluga#289]
While browsing URL : `http://beluga.com/ticketTest/browsePage`
```
uncaught exception: Error while executing SELECT * from beluga_tic_ticket ORDER BY date DESC (Unknown column 'date' in 'order clause')

in file: C:\HaxeToolkit\haxe\lib\beluga\Beluga\test\bin\php\lib\php\db\_PDO\PDOConnection.class.php line 34
#0 C:\HaxeToolkit\haxe\lib\beluga\Beluga\test\bin\php\lib\beluga\module\ticket\Ticket.class.php(30): php_db__PDO_PDOConnection->request('SELECT * from b...')
#1 C:\HaxeToolkit\haxe\lib\beluga\Beluga\test\bin\php\lib\beluga\module\ticket\widget\Browse.class.php(12): beluga_module_ticket_Ticket->getTickets()
#2 C:\HaxeToolkit\haxe\lib\beluga\Beluga\test\bin\php\lib\beluga\widget\MttWidget.class.php(64): beluga_module_ticket_widget_Browse->getContext()
#3 C:\HaxeToolkit\haxe\lib\beluga\Beluga\test\bin\php\lib\beluga\widget\MttWidget.class.php(13): beluga_widget_MttWidget_0(Object(beluga_module_ticket_widget_Browse))
#4 C:\HaxeToolkit\haxe\lib\beluga\Beluga\test\bin\php\lib\modules\ticket_test\TicketTest.class.php(25): beluga_widget_MttWidget->render()
#5 [internal function]: modules_ticket_test_TicketTest->doBrowsePage()
#6 C:\HaxeToolkit\haxe\lib\beluga\Beluga\test\bin\php\lib\Reflect.class.php(12): call_user_func_array(Array, Array)
#7 C:\HaxeToolkit\haxe\lib\beluga\Beluga\test\bin\php\lib\haxe\web\Dispatch.class.php(51): Reflect::callMethod(Object(modules_ticket_test_TicketTest), Array, Object(_hx_array))
#8 C:\HaxeToolkit\haxe\lib\beluga\Beluga\test\bin\php\lib\Main.class.php(18): haxe_web_Dispatch->runtimeDispatch(Object(_hx_anonymous))
#9 [internal function]: Main->doDefault('ticketTest', Object(haxe_web_Dispatch))
#10 C:\HaxeToolkit\haxe\lib\beluga\Beluga\test\bin\php\lib\Reflect.class.php(12): call_user_func_array(Array, Array)
#11 C:\HaxeToolkit\haxe\lib\beluga\Beluga\test\bin\php\lib\haxe\web\Dispatch.class.php(51): Reflect::callMethod(Object(Main), Array, Object(_hx_array))
#12 C:\HaxeToolkit\haxe\lib\beluga\Beluga\test\bin\php\lib\Main.class.php(94): haxe_web_Dispatch->runtimeDispatch(Object(_hx_anonymous))
#13 C:\HaxeToolkit\haxe\lib\beluga\Beluga\test\bin\php\index.php(9): Main::main()
#14 {main}
```

**Comment by GuillaumeGomez** [comment]
I take a look at it.

**Comment by GuillaumeGomez** [comment]
I didn't find any issue or problem. Update your database and try again.
